# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54dbbd194f0d789e2c9b92673d522001ddbeec2a656b6bd8f405dd79b86563881ab6ed941f52dbfc8b818e917da3011862695de6b6e90c17cb3244e93036fde1

test:
  secret_key_base: 7976299f7ac22361d70baa7f936a251e89ef34cfc2f14769dca3e71005beb8565005177c1dd9fd29156562b86ce329bd1f29c66c14ec064830fc786ed9a6928a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
